default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: peoplebook_development

test:
  <<: *default
  database: peoplebook_test

production:
  <<: *default
  database: peoplebook_production
  username: peoplebook
  password: <%= ENV["PEOPLEBOOK_DATABASE_PASSWORD"] %>
